name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to homelab
        run: |
          cd /home/homelab/docker/code-server/config/workspace/projects/auth
          git pull origin main
